using NuGet.Protocol.Plugins;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FinalExamSystems
{
    /// <summary>
    /// Customer Service Controller - Concrete Controller for Customer Services requirements, inherit from Service Controller abstract class
    /// </summary>
    public class CustomerServicesController : ServicesController
    {
        /// <summary>
        /// historic is an instance of SErvice Historic which is an association class between Services and User
        /// </summary>
        private ServicesHistory historic = new ServicesHistory();
        /// <summary>
        /// service is an instance of Customer Service class
        /// </summary>
        private CustomerServices service = new CustomerServices();

        /// <summary>
        /// Service property
        /// </summary>
        public Service Service
        {
            get => service; set => service = (CustomerServices)value;
        }


        /// <summary>
        /// Override CollectUserData method to get from the UI the user inputs following the definition of controller pattern GRASP
        /// </summary>
        public override void CollectUserData()
        {
            //Read User - Customer Information from UI View
            /* --- DATA INPUT EXAMPLE
            string origin  = originTextField.Text;
            string destination = destinationTextField.Text;
            DateTime departureDate = DateTime.Parse(departureTextField.Text);
            DateTime returnDate = DateTime.Parse(returnTextField.Text);
             */
        }


#pragma warning disable CS1572 // XML comment has a param tag, but there is no parameter by that name
        /// <summary>
        /// SearchFlight_Click is the event generated by a button on an UI interface
        /// </summary>
        /// <param name="sender">Sender parameter is the element on IU which generates the Event</param>
        public void SearchFlight_Click()//read the event fron the sender -- Sender: Object)
#pragma warning restore CS1572 // XML comment has a param tag, but there is no parameter by that name
        {
            CollectUserData();
            string origin = "";// = originTextField.Text;
            string destination = ""; //= destinationTextField.Text;
            DateTime departureDate = DateTime.Now; // = DateTime.Parse(departureTextField.Text);
            DateTime returnDate = DateTime.Now; // = DateTime.Parse(returnTextField.Text);
            //call search flight service from customer service instance -- handling petition
            List<Flight> availableFlights = service.searchFlight(origin, destination, departureDate, returnDate);
            LinkServiceToUser();
            /* return response to customer UI interface
            flightsList.Add(availableFlights);
            */
        }

#pragma warning disable CS1572 // XML comment has a param tag, but there is no parameter by that name
        /// <summary>
        /// ReserveTicket_Click is the event generated by a button on an UI interface
        /// </summary>
        /// <param name="sender">Sender parameter is the element on IU which generates the Event</param>
        public void ReserveTicket_Click()//read the event fron the sender -- Sender: Object)
#pragma warning restore CS1572 // XML comment has a param tag, but there is no parameter by that name
        {
            CollectUserData();
            //calling service class to handle the information
            service.ReserveTicket();
            LinkServiceToUser();
            /* return response to customer UI interface
            */
        }

#pragma warning disable CS1572 // XML comment has a param tag, but there is no parameter by that name
        /// <summary>
        /// PurchaseTicket_Click is the event generated by a button on an UI interface
        /// </summary>
        /// <param name="sender">Sender parameter is the element on IU which generates the Event</param>
        public void PurchaseTicket_Click()//read the event fron the sender -- Sender: Object)
#pragma warning restore CS1572 // XML comment has a param tag, but there is no parameter by that name
        {
            CollectUserData();
            //calling service class to handle the information
            service.PurchaseTicket();
            LinkServiceToUser();
            /* return response to customer UI interface
            */
        }

#pragma warning disable CS1572 // XML comment has a param tag, but there is no parameter by that name
        /// <summary>
        /// CancelTicket_Click is the event generated by a button on an UI interface
        /// </summary>
        /// <param name="sender">Sender parameter is the element on IU which generates the Event</param>
        public void CancelTicket_Click()//read the event fron the sender -- Sender: Object)
#pragma warning restore CS1572 // XML comment has a param tag, but there is no parameter by that name
        {
            CollectUserData();
            //calling service class to handle the information
            service.CancelTicket();
            LinkServiceToUser();
            /* return response to customer UI interface        */
        }

        /// <summary>
        /// Controller link the service to user when the service is triggered from UI
        /// </summary>
        public override void LinkServiceToUser()
        {
            historic.Service = service;
        }


        /*
         * Additional action handlers depending on the actions provided on the UI for customer services view
         */

    }
}