using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FinalExamSystems
{
    /// <summary>
    /// Applying Controller pattern
    /// Provision Service Controller - Concrete Controller for Provision Services requirements, inherit from Service Controller abstract class
    /// </summary>
    public class ProvisionServicesController : ServicesController
    {
        /// <summary>
        /// historic is an instance of Service Historic which is an association class between Services and User
        /// </summary>
        private ServicesHistory historic = new ServicesHistory();
        /// <summary>
        /// service is an instance of Customer Service class
        /// </summary>
        private ProvisionServices service = new ProvisionServices();

        /// <summary>
        /// Service Property
        /// </summary>
        public Service Service
        {
            get => service; set => service = (ProvisionServices)value;
        }

        /// <summary>
        /// Override CollectUserData method to get from the UI the user inputs following the definition of controller pattern GRASP
        /// </summary>
        public override void CollectUserData()
        {
            //Read User - Customer Information from UI View
            /* --- DATA INPUT EXAMPLE
            string origin  = originTextField.Text;
            string destination = destinationTextField.Text;
            DateTime departureDate = DateTime.Parse(departureTextField.Text);
            DateTime returnDate = DateTime.Parse(returnTextField.Text);
             */
        }

#pragma warning disable CS1572 // XML comment has a param tag, but there is no parameter by that name
        /// <summary>
        /// AddPlanesToAirline_Click is the event generated by a button on an UI interface
        /// </summary>
        /// <param name="sender">Sender parameter is the element on IU which generates the Event</param>
        public void AddPlanesToAirline_Click()//read the event fron the sender -- Sender: Object)
#pragma warning restore CS1572 // XML comment has a param tag, but there is no parameter by that name
        {
            CollectUserData();
            //calling service class to handle the information
            service.AddPlaneToAirline();
            LinkServiceToUser();
            /* return response to customer UI interface
            */
        }

#pragma warning disable CS1572 // XML comment has a param tag, but there is no parameter by that name
        /// <summary>
        /// AddClassesFlight_Click is the event generated by a button on an UI interface
        /// </summary>
        /// <param name="sender">Sender parameter is the element on IU which generates the Event</param>
        public void AddClassesFlight_Click()//read the event fron the sender -- Sender: Object)
#pragma warning restore CS1572 // XML comment has a param tag, but there is no parameter by that name
        {
            CollectUserData();
            //calling service class to handle the information
            service.AddFlightClass();
            LinkServiceToUser();
            /* return response to customer UI interface
            */
        }

#pragma warning disable CS1572 // XML comment has a param tag, but there is no parameter by that name
        /// <summary>
        /// ScheduleFlight_Click is the event generated by a button on an UI interface
        /// </summary>
        /// <param name="sender">Sender parameter is the element on IU which generates the Event</param>
        public void ScheduleFlight_Click()//read the event fron the sender -- Sender: Object)
#pragma warning restore CS1572 // XML comment has a param tag, but there is no parameter by that name
        {
            CollectUserData();
            //calling service class to handle the information
            service.ScheduleFlight();
            LinkServiceToUser();
            /* return response to customer UI interface
            */
        }


        /// <summary>
        /// Controller link the service to user when the service is triggered from UI
        /// </summary>
        public override void LinkServiceToUser()
        {
            historic.Service = service;
        }
    }
}